<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lms.Data\Lms.Data.csproj" />
    <ProjectReference Include="..\Lms.Infrastructure\Lms.Infrastructure.csproj" />
  </ItemGroup>

</Project>
